 name: Build & Test CI

on: push

jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn
            - name: Build packages
              run: yarn build
            - name: Automated tests
              run: yarn test